トップページのデザイン変更
takeyuwebinc/gitfab2 pull request #89
Opened 2019-02-13 01:57 UTC by bumberboom

データの埋め込みはまだなので、どなたかお願いします。

【データがまだ反映されていない箇所】
- Usage Data 3つ（「こんな用途に」の下部）
- POPULAR PROJECTS のプロジェクトを人気順にする
- POPULAR PROJECTS のプロジェクトを10個までにする
- 最近のプロジェクトの場合は順位バッジを非表示にする

2019-02-13 03:13 UTC, takeyuweb commented
以下の各ブラウザで崩れないことを確認しました。

- Windows 7 + IE 11
  - サポート期限 2020年1月14日
- Windows 10 + Edge
- Windows 10 + Firefox
- Windows 10 + Chrome
- macOS Sierra + Safari 10.1
  - macOS のサポート期限は非公開だが、おおむね最新の２つ前までということだたので、Sierra

以下のブラウザでは崩れるようです。
- iOS 11 + Safari 11 (iPad 5th)
- iOS 12 + Safari 12 (iPad 6th)

| 現行 | 本PR |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/60980/52684181-aa41af80-2f88-11e9-9c10-5ce130f52488.png) | ![image](https://user-images.githubusercontent.com/60980/52684074-3e5f4700-2f88-11e9-8d8f-f308dbd572eb.png) |

2019-02-13 03:49 UTC, takeyuweb requested changes
全体の直しにはならなそうなら、いったんマージして組み込み実装しつつ、PRでiPad対応してもよいと思いますが、どうでしょうか？

すぐに修正できそうならここで直してしまってもよいです。

2019-02-13 05:27 UTC, itkrt2y commented
flexboxの都合上、projectsの個数によっては以下の画像のように最後の行は変な配置されますが、「POPULAR PROJECTS のプロジェクトを10個までにする」とかはもう10個固定にして対応ってことでいいのでしょうか？

![image](https://user-images.githubusercontent.com/2343568/52688839-673d0780-2f9b-11e9-9eb5-29ce4a21181b.png)

2019-02-13 05:36 UTC, bumberboom commented
> flexboxの都合上、projectsの個数によっては以下の画像のように最後の行は変な配置されますが、「POPULAR PROJECTS のプロジェクトを10個までにする」とかはもう10個固定にして対応ってことでいいのでしょうか？

はい、今回はトップ10決め打ちでいいので、数が半端になったときのことは考慮しないことにします。

2019-02-13 12:58 UTC, bumberboom commented
@takeyuweb iPad でのレイアウト崩れを修正しました。

2019-02-14 02:58 UTC, itkrt2y commented
他の作業の兼ね合いもあるので、とりあえずマージしちゃいます。まだ問題があれば別PRで

2019-02-14 02:58 UTC, merged